name: vinted
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  http: ^1.2.1
  provider: ^6.1.2
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  dio: ^5.5.0+1
  image_picker: ^1.1.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icon.jpg
