// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6uYEG5xKfR1Pw895VwevOj2dPLyZu-24',
    appId: '1:16750052925:web:f4357cf51425a1176a4c54',
    messagingSenderId: '16750052925',
    projectId: 'vinted-osc-db310',
    authDomain: 'vinted-osc-db310.firebaseapp.com',
    storageBucket: 'vinted-osc-db310.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKcFS3jK5eeg166QjrX9MonkODa7X2b4A',
    appId: '1:16750052925:android:2566e5a62c671a606a4c54',
    messagingSenderId: '16750052925',
    projectId: 'vinted-osc-db310',
    storageBucket: 'vinted-osc-db310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsja6quejYoQKzNiVUVC3aTLdiUq7p6FU',
    appId: '1:16750052925:ios:b215a1e9f055bcde6a4c54',
    messagingSenderId: '16750052925',
    projectId: 'vinted-osc-db310',
    storageBucket: 'vinted-osc-db310.appspot.com',
    iosBundleId: 'com.example.vinted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsja6quejYoQKzNiVUVC3aTLdiUq7p6FU',
    appId: '1:16750052925:ios:b215a1e9f055bcde6a4c54',
    messagingSenderId: '16750052925',
    projectId: 'vinted-osc-db310',
    storageBucket: 'vinted-osc-db310.appspot.com',
    iosBundleId: 'com.example.vinted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6uYEG5xKfR1Pw895VwevOj2dPLyZu-24',
    appId: '1:16750052925:web:fce9e311266740096a4c54',
    messagingSenderId: '16750052925',
    projectId: 'vinted-osc-db310',
    authDomain: 'vinted-osc-db310.firebaseapp.com',
    storageBucket: 'vinted-osc-db310.appspot.com',
  );
}
