// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfwqs7yTOrf-NRlUOkgKb-IaIV-GXDeu0',
    appId: '1:132922718628:web:182fe848cfb3d1c315e931',
    messagingSenderId: '132922718628',
    projectId: 'vinted-osc-bfb4d',
    authDomain: 'vinted-osc-bfb4d.firebaseapp.com',
    databaseURL: 'https://vinted-osc-bfb4d-default-rtdb.firebaseio.com',
    storageBucket: 'vinted-osc-bfb4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJIDnqEPQOOMUEaewKPQ2MqBd4SPa628',
    appId: '1:132922718628:android:e6bb2683315e781815e931',
    messagingSenderId: '132922718628',
    projectId: 'vinted-osc-bfb4d',
    databaseURL: 'https://vinted-osc-bfb4d-default-rtdb.firebaseio.com',
    storageBucket: 'vinted-osc-bfb4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl8w3ym_MFXQhm3LJUKQsL6_EWnILa1uA',
    appId: '1:132922718628:ios:431897bab97f997a15e931',
    messagingSenderId: '132922718628',
    projectId: 'vinted-osc-bfb4d',
    databaseURL: 'https://vinted-osc-bfb4d-default-rtdb.firebaseio.com',
    storageBucket: 'vinted-osc-bfb4d.appspot.com',
    iosBundleId: 'com.example.vinted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl8w3ym_MFXQhm3LJUKQsL6_EWnILa1uA',
    appId: '1:132922718628:ios:431897bab97f997a15e931',
    messagingSenderId: '132922718628',
    projectId: 'vinted-osc-bfb4d',
    databaseURL: 'https://vinted-osc-bfb4d-default-rtdb.firebaseio.com',
    storageBucket: 'vinted-osc-bfb4d.appspot.com',
    iosBundleId: 'com.example.vinted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfwqs7yTOrf-NRlUOkgKb-IaIV-GXDeu0',
    appId: '1:132922718628:web:83b1ac099fd2996c15e931',
    messagingSenderId: '132922718628',
    projectId: 'vinted-osc-bfb4d',
    authDomain: 'vinted-osc-bfb4d.firebaseapp.com',
    databaseURL: 'https://vinted-osc-bfb4d-default-rtdb.firebaseio.com',
    storageBucket: 'vinted-osc-bfb4d.appspot.com',
  );

}